version: "3"
services:
  app:
     image: 'infracloudio/csvserver'
     environment:
       -  CSVSERVER_BORDER= Orange 
     volumes:
       - './inputFile:/csvserver/inputdata' 
     ports:
     - 9393:9300
    
  
  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus_db:/var/lib/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    ports:
     - '9100:9100'