global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['192.168.43.138:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['192.168.43.138:9100']
  - job_name: 'container_metrics' 
    static_configs: 
      - targets: ['192.168.43.138:9323']
  - job_name: 'csvserver_records ' 
    static_configs: 
      - targets: ['192.168.43.138:9393']